
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-4.9
script:
  - export CXX="g++-4.9" CC="gcc-4.9"
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest
